use_frameworks!

# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'


target 'Demo' do

pod 'ColorPinAnnotationView', :path => '..' 

end


target 'DemoTests' do

end

